'use strict';
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('relay', {
  getVersion: () => ipcRenderer.invoke('getVersion'),
  getConfig: () => ipcRenderer.invoke('getConfig'),
  addPairing: (patch) => ipcRenderer.invoke('addPairing', patch),
  removePairing: (i) => ipcRenderer.invoke('removePairing', i),
  saveLogPath: (p) => ipcRenderer.invoke('saveLogPath', p),
  saveLogBackupsPath: (p) => ipcRenderer.invoke('saveLogBackupsPath', p),
  start: () => ipcRenderer.invoke('start'),
  stop: () => ipcRenderer.invoke('stop'),
  digest: () => ipcRenderer.invoke('digest'),
  catchUp: () => ipcRenderer.invoke('catchUp'),
  haul: () => ipcRenderer.invoke('haul'),
  onStatus: (cb) => ipcRenderer.on('status', (_e, line) => cb(line)),
  onRefresh: (cb) => ipcRenderer.on('refresh', () => cb()),
  onUpdateReady: (cb) => ipcRenderer.on('update-ready', (_e, info) => cb(info)),
  onUpdateDownloading: (cb) => ipcRenderer.on('update-downloading', (_e, info) => cb(info)),
  installUpdate: () => ipcRenderer.invoke('installUpdate'),
  getUI: () => ipcRenderer.invoke('getUI'),
  setUI: (ui) => ipcRenderer.invoke('setUI', ui),
  onShortcut: (cb) => ipcRenderer.on('shortcut', (_e, a) => cb(a)),
  getLoginItem: () => ipcRenderer.invoke('getLoginItem'),
  setLoginItem: (on) => ipcRenderer.invoke('setLoginItem', on),
  getSound: () => ipcRenderer.invoke('getSound'),
  setSound: (on) => ipcRenderer.invoke('setSound', on),
  onHealth: (cb) => ipcRenderer.on('health', (_e, h) => cb(h)),
});
